# Generated by Django 3.2.6 on 2021-08-10 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_skin_concern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skin_concern',
        ),
    ]
