# Generated by Django 3.2.6 on 2021-08-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='treatment_type',
            field=models.CharField(choices=[('Dryness', 'Dryness'), ('Oily', 'Oily'), ('Acne', 'Acne'), ('Aging', 'Aging'), ('Rosacea', 'Rosacea'), ('None', 'None')], default='NONE', max_length=20),
        ),
    ]
